name: lint-test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: shellcheck
        run: shellcheck scripts/*.sh

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: latest
  test:
    needs: [lint]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: false
          tags: |
            ezproxy-url-checker:ci

      - name: Run tests
        shell: bash
        run: |-
          ./scripts/generate-files.sh $(pwd)/fixtures
          CONTAINER=$(docker run \
            --rm \
            -d \
            -v $(pwd)/config:/app/config \
            ezproxy-url-checker:ci)
          docker logs $CONTAINER
          docker exec $CONTAINER /bin/bash /app/scripts/test.sh
          docker stop $CONTAINER
  build-push-ghcr:
    needs: [test]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit

